services:
  shop.api:
    image: ${DOCKER_REGISTRY-}shopapi
    container_name: shop.api
    build:
      context: .
      dockerfile: Shop.Api/Dockerfile
    depends_on:
      - shop.db
    ports: 
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=shop.db;Database=ShopDB;User Id=sa;Password=Teste@2024;MultipleActiveResultSets=True;Encrypt=False 

  shop.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shop.db
    ports:
      - "1433:1433"
    restart: always
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "Teste@2024"
      ACCEPT_EULA: "Y"
    volumes:
      - shopdata:/var/opt/mssql

volumes:
  shopdata: